# Generated by Django 3.2.8 on 2021-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_SKU', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('actions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Actions')),
            ],
        ),
    ]
