# Generated by Django 3.2 on 2021-07-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquamamachine',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotspots.location', verbose_name='location'),
        ),
    ]
