# Generated by Django 3.2 on 2021-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_alter_aquamamachine_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquamamachine',
            name='bluetooth_name',
            field=models.CharField(max_length=255, verbose_name='bluetooth name'),
        ),
        migrations.AlterField(
            model_name='aquamamachine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
