# Generated by Django 3.2 on 2021-07-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0003_auto_20210715_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquamamachine',
            name='origin',
            field=models.CharField(choices=[('here', 'Here'), ('hydro', 'Hydro'), ('csv', 'Import CSV')], default='here', help_text='from where this machin was created', max_length=5, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='aquamamachine',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspots.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='aquamamachine',
            name='wwan_available',
            field=models.BooleanField(default=True, verbose_name='WWAN available'),
        ),
        migrations.AlterField(
            model_name='aquamapointofsale',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspots.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
