# Generated by Django 3.2 on 2021-07-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0004_auto_20210727_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aquamamachine',
            options={'ordering': ['serial_number'], 'verbose_name': 'Aquama machine', 'verbose_name_plural': 'Aquama machines'},
        ),
    ]
