# Generated by Django 3.2 on 2021-08-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0006_auto_20210816_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquamamachine',
            name='rfid_reader_enabled',
            field=models.BooleanField(default=False, verbose_name='RFID reader enabled'),
        ),
    ]
