# Generated by Django 3.2 on 2021-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0007_aquamamachine_rfid_reader_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquamapointofsale',
            name='name',
            field=models.CharField(default='No name', max_length=255, verbose_name='name'),
        ),
    ]
